import { chromium } from 'playwright';
import fs from 'node:fs';
const F=JSON.parse(fs.readFileSync('/tmp/p360nav/fixture.json','utf8'));
const PW=fs.readFileSync('/tmp/p360nav/.pw','utf8').trim();
const ORIGIN='http://127.0.0.1:4420', TEST='https://test.emarketingacademy.net', TUN='http://127.0.0.1:15091';
const b=await chromium.launch(); const c=await b.newContext(); const p=await c.newPage();
const fwd=async r=>{const q=r.request();const u=new URL(q.url());const h={...q.headers()};delete h.host;delete h.origin;delete h.referer;
 const res=await fetch(TUN+u.pathname+u.search,{method:q.method(),headers:h,body:q.postData()??undefined});
 r.fulfill({status:res.status,body:Buffer.from(await res.arrayBuffer()),headers:{'content-type':res.headers.get('content-type')??'application/json'}});};
await p.route(`${TEST}/api/**`,fwd); await p.route(`${TEST}/hubs/**`,fwd);
await p.goto(`${ORIGIN}/login`); await p.locator('input[type=email]').fill(F.users.admin.email);
await p.locator('input[type=password]').fill(PW); await p.locator('button[type=submit]').first().click();
await p.waitForURL(u=>!u.pathname.endsWith('/login'),{timeout:20000});
await p.goto(`${ORIGIN}/app/projects/${F.projectA}/360`,{waitUntil:'networkidle'});
await p.waitForTimeout(1500);
console.log('URL:',p.url());
console.log('H1:',await p.locator('h1').allInnerTexts());
console.log('TABS:',await p.locator('[aria-label="أقسام مساحة عمل المشروع"]').count());
console.log('has_360_link:',await p.getByRole('link',{name:'مساحة عمل المشروع (360)'}).count());
console.log('TEXT_HEAD:',(await p.locator('body').innerText()).slice(0,400).replace(/\n+/g,' | '));
await b.close();
